spring.application.name=app

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/xuexi_hanyu
spring.datasource.username=postgres
spring.datasource.password=7324*Tan
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080
